### ISSUE TITLE
Race Condition in ModularMultiExampleCooker

### ISSUE THREAD

**Issue by malcolmgreaves** [TeamCohen/ProPPR#4]
When I run the grounding script with --threads k (where k is > 1), I get this error:

 INFO [Component] Loading from file 'kbp_prototype/doc.crules' with alpha=0.0 ...
 INFO [Component] Loading from file 'kbp_prototype/tac_kbp.crules' with alpha=0.0 ...
 INFO [Component] Loading from file 'kbp_prototype/lp_predicate_SF_ENG_001-q+answer.cfacts' with alpha=0.0 ...
 INFO [Component] Loading from file 'kbp_prototype/lp_predicate_SF_ENG_001-q+answer.graph' with alpha=0.0 ...
Exception in thread "main" java.lang.NullPointerException
        at edu.cmu.ml.praprolog.prove.RawPosNegExampleStreamer$RawExampleIterator.peek(RawPosNegExampleStreamer.java:103)
        at edu.cmu.ml.praprolog.prove.RawPosNegExampleStreamer$RawExampleIterator.next(RawPosNegExampleStreamer.java:122)
        at edu.cmu.ml.praprolog.prove.RawPosNegExampleStreamer$RawExampleIterator.next(RawPosNegExampleStreamer.java:69)
        at edu.cmu.ml.praprolog.ModularMultiExampleCooker.cookExamples(ModularMultiExampleCooker.java:31)
        at edu.cmu.ml.praprolog.ExampleCooker.cookExamples(ExampleCooker.java:54)
        at edu.cmu.ml.praprolog.ExampleCooker.main(ExampleCooker.java:44)

This error occurs even if --nthreads 1 is used.

If I run the same script with no --threads option, everything works fine.

This was not an error until I updated to revision 51744b1 .

For good measure, I ran ant test to see if any tests failed with this behavior -- none did.

**Comment by krivard** [comment]
Should be fixed in b01bd60317. Testcase showing the bug is in testcases/regression.sh, which I've added to my pre-commit checklist. Verify it works for you and close?

**Comment by malcolmgreaves** [comment]
Verified. Error gone with b01bd60 ! =D
